CREATE TABLE IF NOT EXISTS DOMINO(
  idDomino  INT(11) AUTO_INCREMENT NOT NULL,
  PRIMARY KEY(idDomino)
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS CASES(
  noCase INT(11) AUTO_INCREMENT NOT NULL,
  nbCouronne INT,
  paysage VARCHAR(8),
  idDomino INT,
  PRIMARY KEY(noCase),
  CONSTRAINT FK_CASES_idDomino_fk
		FOREIGN KEY (idDomino) REFERENCES DOMINO(idDomino),
		CONSTRAINT FK_CASES_paysage_fk
		FOREIGN KEY (paysage) REFERENCES PAYSAGE(nom)
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS PAYSAGE(
  nom VARCHAR(8),
  PRIMARY KEY(nom)
);